name = "waifuim-bot"
main = "dist/worker.mjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_TOKEN = "8569602310:AAFCCG7odOeHD9QfpdNZl957WcthmXf-Zs8"
ADMIN_TELEGRAM_ID = "317520896"
WAIFU_API_KEY = "DzZmtP2q001wUEOjRGNlKWY0nDk8STrtktevRWbdoQ"
NSFW_ALLOWED = "true"

[[d1_databases]]
binding = "DB"
database_name = "waifuim-bot-db"
database_id = "11928565-88fd-4e0b-960d-78bc311ab32c"

[build]
command = "node build-worker.mjs"
